### ISSUE TITLE
Readme leads to errors

### ISSUE THREAD

**Issue by Konafets** [Sylius/PluginSkeleton#141]
After cloning this repo I went to the `tests/Appliation` folder and followed the instruction in the README. Therefore I did

* `yarn install` -> works fine
* `yarn build` -> errors:

```shell
yarn run v1.10.1
$ gulp build
[12:53:17] Failed to load external module @babel/register
[12:53:17] Requiring external module babel-register
[12:53:18] Using gulpfile ~/Development/Sylius/PluginSkeleton/tests/Application/gulpfile.babel.js
[12:53:18] Starting 'build'...
[12:53:18] Starting 'buildAdmin'...
[12:53:18] Starting 'buildShop'...
[12:53:18] 'buildAdmin' errored after 19 ms
[12:53:18] Error: File not found with singular glob: /Users/sok/Development/Sylius/PluginSkeleton/tests/Application/../../vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/gulpfile.babel.js (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/Users/sok/Development/Sylius/PluginSkeleton/tests/Application/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:273:13)
    at Glob.emit (events.js:182:13)
    at Glob.EventEmitter.emit (domain.js:442:20)
    at Glob._finish (/Users/sok/Development/Sylius/PluginSkeleton/tests/Application/node_modules/glob/glob.js:197:8)
    at done (/Users/sok/Development/Sylius/PluginSkeleton/tests/Application/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/Users/sok/Development/Sylius/PluginSkeleton/tests/Application/node_modules/glob/glob.js:688:12)
    at /Users/sok/Development/Sylius/PluginSkeleton/tests/Application/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/Users/sok/Development/Sylius/PluginSkeleton/tests/Application/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/Users/sok/Development/Sylius/PluginSkeleton/tests/Application/node_modules/glob/glob.js:764:12)
[12:53:18] 'build' errored after 26 ms
[12:53:18] The following tasks did not complete: buildShop
[12:53:18] Did you forget to signal async completion?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Zales0123** [comment]
Did you run `cd tests/Application` and then `yarn install` or (as it's in the instruction) `(cd tests/Application && yarn install)`?

**Comment by Konafets** [comment]
There is the full log of what I am doing:

```bash
$ git clone git@github.com:Sylius/PluginSkeleton.git
Cloning into 'PluginSkeleton'...
remote: Enumerating objects: 27, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 1225 (delta 7), reused 22 (delta 6), pack-reused 1198
Receiving objects: 100% (1225/1225), 391.71 KiB | 932.00 KiB/s, done.
Resolving deltas: 100% (520/520), done.

$ cd PluginSkeleton

$ (cd tests/Application && yarn install)                                                                                                                                      
yarn install v1.10.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
warning gulp-chug > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
warning gulp-debug > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
warning gulp-livereload > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 125.34s.

$ (cd tests/Application && yarn build)                                                                                                                                         
yarn run v1.10.1
$ gulp build
[13:26:23] Failed to load external module @babel/register
[13:26:23] Requiring external module babel-register
[13:26:25] Using gulpfile ~/Development/Sylius/PluginSkeleton/tests/Application/gulpfile.babel.js
[13:26:25] Starting 'build'...
[13:26:25] Starting 'buildAdmin'...
[13:26:25] Starting 'buildShop'...
[13:26:25] 'buildAdmin' errored after 19 ms
[13:26:25] Error: File not found with singular glob: /Users/sok/Development/Sylius/PluginSkeleton/tests/Application/../../vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/gulpfile.babel.js (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/Users/sok/Development/Sylius/PluginSkeleton/tests/Application/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:273:13)
    at Glob.emit (events.js:182:13)
    at Glob.EventEmitter.emit (domain.js:442:20)
    at Glob._finish (/Users/sok/Development/Sylius/PluginSkeleton/tests/Application/node_modules/glob/glob.js:197:8)
    at done (/Users/sok/Development/Sylius/PluginSkeleton/tests/Application/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/Users/sok/Development/Sylius/PluginSkeleton/tests/Application/node_modules/glob/glob.js:688:12)
    at /Users/sok/Development/Sylius/PluginSkeleton/tests/Application/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/Users/sok/Development/Sylius/PluginSkeleton/tests/Application/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/Users/sok/Development/Sylius/PluginSkeleton/tests/Application/node_modules/glob/glob.js:764:12)
[13:26:25] 'build' errored after 24 ms
[13:26:25] The following tasks did not complete: buildShop
[13:26:25] Did you forget to signal async completion?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Konafets** [comment]
My mistake was to clone the repo and not to use `composer create-project`. With this it works.
